version: '3.9'
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.57.0/24
services:
  elixir-hello:
    container_name: elixir-hello
    build:
      context: .
    ports:
      - 4000:4000
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.41
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
